#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo "钩子生效"

# marray=`git status -s`
# echo $marray 

# echo $marray  -> text.json

FILE_PATH="./app/" #  xxx：路径

cd $FILE_PATH

tempNames=`ls`

cd '../'
echo -e $tempNames > appname.text

git add .

# echo -e "abc \n bcd" > text.json

exit 0
